In [25]:
import numpy as np

#### 1. Crear un vector con valores dentro del rango 10 a 49

In [26]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 2. Invertir el vector

In [27]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 3. Crear una matriz 3x3 con valores de 0 a 8

In [28]:
matriz = [[0,1,2], [3,4,5], [6,7,8]]
matriz

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

#### 4. Crear una matriz con valores al azar con forma 3x3x3

In [29]:
a = np.random.rand(3,3,3)
a

array([[[0.98906773, 0.1103843 , 0.78437469],
        [0.40213665, 0.21276834, 0.60118307],
        [0.03119501, 0.99406432, 0.35707264]],

       [[0.19867967, 0.5863126 , 0.72426809],
        [0.01980173, 0.43002853, 0.62381669],
        [0.35193072, 0.42892958, 0.7958186 ]],

       [[0.90747544, 0.04315424, 0.44885369],
        [0.06307082, 0.73363242, 0.76255608],
        [0.58287911, 0.90365192, 0.17393866]]])

#### 5. Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de índices)

In [30]:
a = np.ones((10,10))

a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 6. Crear una matriz de 5 x 4.

In [31]:
a = np.random.randn(4,5)
a

array([[-0.09566578, -0.21236688,  0.1682379 , -0.67612168, -0.19219985],
       [-2.20101841,  0.67198319,  1.06434846, -0.05520223,  1.27748507],
       [ 0.51253724,  0.88460041,  0.11809591, -0.15505357, -0.17565555],
       [ 0.79080726,  1.29018962, -0.16927932, -0.18343511,  0.47930923]])

    6.1 Muestra los valores máximos por columna

In [32]:
col0 = [fila[0] for fila in a]
col1 = [fila[1] for fila in a]
col2 = [fila[2] for fila in a]
col3 = [fila[3] for fila in a]
print(np.amax(col0))
print(np.amax(col1))
print(np.amax(col2))
print(np.amax(col3))

0.7908072559154874
1.290189618149556
1.064348459335388
-0.055202234571432675


    6.2 Muestra los valores mínimos por columna


In [33]:
print(np.amin(col0))
print(np.amin(col1))
print(np.amin(col2))
print(np.amin(col3))

-2.2010184069440766
-0.2123668752269648
-0.1692793157011714
-0.6761216841902072


    6.3 Muestra los valores máximos por fila


In [34]:
print(np.amax(a[:1]))
print(np.amax(a[1:2]))
print(np.amax(a[2:3]))
print(np.amax(a[3:4]))

0.16823790139168576
1.2774850745216897
0.8846004073607121
1.290189618149556


    6.4 Muestra los valores mínimos por fila


In [35]:
print(np.amin(a[:1]))
print(np.amin(a[1:2]))
print(np.amin(a[2:3]))
print(np.amin(a[3:4]))

-0.6761216841902072
-2.2010184069440766
-0.1756555465612888
-0.183435111454413


    6.5 Muestra el valor máximo


In [36]:
np.amax(a)

1.290189618149556

    6.6 Muestra el valor mínimo


In [37]:
np.amin(a)

-2.2010184069440766

    6.7 Muestra la posición del máximo

In [38]:
np.argmax(a)


16

    6.8 Muestra la posición del mínimo


In [39]:
np.argmin(a)

5

#### 7. Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla una serie con los datos de las ventas indexada por los años, antes y después de aplicarles un descuento del 10%. (Nota: con que preguntes dos años, es más que suficiente)


In [121]:
fecha1 = int(input("Fecha 1:"))
fecha2 = int(input("Fecha 2:"))
b =np.arange(fecha1, fecha2)
fechas = {
    2010: {
        "ventas": 220
    },
    2011: {
        "ventas": 231
    },
    2012: {
        "ventas": 184
    },
    2013: {
        "ventas": 265
    },
    2014: {
        "ventas": 284
    }
}
precio_inicial = []
descuento = []
for i in b: 
    precio_inicial.append(fechas[i]["ventas"])
descuento.append(np.multiply(precio_inicial,0.10))
precio_final = np.subtract(precio_inicial, descuento)
# print(precio_inicial)
# print(descuento)
# print(precio_final)

print("Precio inicial: {} \nPrecio con descuento: {}".format(precio_inicial, precio_final))

Precio inicial: [220, 231, 184, 265, 284] 
Precio con descuento: [[198.  207.9 165.6 238.5 255.6]]


In [111]:
a = 1
descuento = 0
print(f"Precio inicial: {a} \nPrecio con descuento: {descuento}")


Precio inicial: 1 
Precio con descuento: 0


#### 8. Escribir una función que reciba un diccionario con las notas de los alumno de un curso y devuelva una serie con la nota mínima, la máxima, media y la desviación típica

In [41]:
notas = {'Jaime':2,
         'Adrián': 10,
         'Pablo': 4,
         'Jorge': 3,
         'David': 7,
         'Manuel': 9,
         'Sara': 6,
         'Lucía': 3}

def calcular_notas(notas):
    nota_max = 0
    nota_min = 10
    for i in notas :
        a = notas.get(i)
        if nota_max < a: nota_max = a
        if nota_min > a: nota_min = a
    
    return "Nota máxima:", nota_max, "Nota mínima:", nota_min,"Nota media:", "Desviación típica:"
calcular_notas(notas)

('Nota máxima:', 10, 'Nota mínima:', 2, 'Nota media:', 'Desviación típica:')

#### 9. Escribir una función que reciba un diccionario con las notas de los alumnos de un curso y devuelva una serie con las notas de los alumnos aprobados ordenadas de mayor a menor.

In [46]:
notas = {'Jaime':2,
         'Adrián': 10,
         'Pablo': 4,
         'Jorge': 3,
         'David': 7,
         'Manuel': 9,
         'Sara': 6,
         'Lucía': 3}

def calcular_notas(notas):
    a = []
    for i in notas :
        a.append(notas.get(i))
    a.sort(reverse = True)
    return a
calcular_notas(notas)

[10, 9, 7, 6, 4, 3, 3, 2]