In [1]:
import numpy as np

#### 1. Crear un vector con valores dentro del rango 10 a 49

In [2]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 2. Invertir el vector

In [3]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 3. Crear una matriz 3x3 con valores de 0 a 8

In [4]:
matriz = [[0,1,2], [3,4,5], [6,7,8]]
matriz

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

#### 4. Crear una matriz con valores al azar con forma 3x3x3

In [5]:
a = np.random.rand(3,3,3)
a

array([[[0.61355915, 0.88213357, 0.83582552],
        [0.395678  , 0.97151381, 0.88568228],
        [0.74902633, 0.28427033, 0.64738181]],

       [[0.10242097, 0.06194152, 0.00765413],
        [0.71576428, 0.54407529, 0.11395935],
        [0.64554089, 0.64308431, 0.53172343]],

       [[0.0895679 , 0.62701847, 0.0037802 ],
        [0.69412695, 0.34491682, 0.28668919],
        [0.71265923, 0.45539189, 0.1815592 ]]])

#### 5. Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de índices)

In [6]:
a = np.ones((10,10))

a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 6. Crear una matriz de 5 x 4.

In [7]:
a = np.random.randn(4,5)
a

array([[-1.19724276, -1.72099968, -0.11557048,  1.38225456,  0.46385693],
       [-0.1960865 ,  0.19274895,  0.54381389,  0.436327  ,  0.91166523],
       [ 1.32363942,  1.82859263, -1.7279439 , -0.6359847 ,  1.43487874],
       [-0.67745602, -0.69389899,  0.0820458 ,  1.36355978,  0.22936853]])

    6.1 Muestra los valores máximos por columna

In [8]:
col0 = [fila[0] for fila in a]
col1 = [fila[1] for fila in a]
col2 = [fila[2] for fila in a]
col3 = [fila[3] for fila in a]
print(np.amax(col0))
print(np.amax(col1))
print(np.amax(col2))
print(np.amax(col3))

1.323639421084759
1.8285926257711702
0.5438138942091879
1.382254562458192


    6.2 Muestra los valores mínimos por columna


In [9]:
print(np.amin(col0))
print(np.amin(col1))
print(np.amin(col2))
print(np.amin(col3))

-1.1972427630648674
-1.7209996795452112
-1.7279438974664654
-0.635984701292265


    6.3 Muestra los valores máximos por fila


In [10]:
print(np.amax(a[:1]))
print(np.amax(a[1:2]))
print(np.amax(a[2:3]))
print(np.amax(a[3:4]))

1.382254562458192
0.9116652268244062
1.8285926257711702
1.363559781493132


    6.4 Muestra los valores mínimos por fila


In [11]:
print(np.amin(a[:1]))
print(np.amin(a[1:2]))
print(np.amin(a[2:3]))
print(np.amin(a[3:4]))

-1.7209996795452112
-0.1960865032201044
-1.7279438974664654
-0.6938989906709203


    6.5 Muestra el valor máximo


In [12]:
np.amax(a)

1.8285926257711702

    6.6 Muestra el valor mínimo


In [13]:
np.amin(a)

-1.7279438974664654

    6.7 Muestra la posición del máximo

In [14]:
np.argmax(a)


11

    6.8 Muestra la posición del mínimo


In [15]:
np.argmin(a)

12

#### 7. Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla una serie con los datos de las ventas indexada por los años, antes y después de aplicarles un descuento del 10%. (Nota: con que preguntes dos años, es más que suficiente)


In [19]:
fecha1 = int(input("Fecha 1:"))
fecha2 = int(input("Fecha 2:"))
b =np.arange(fecha1, fecha2)
fechas = {
    2010: {
        "ventas": 220
    },
    2011: {
        "ventas": 231
    },
    2012: {
        "ventas": 184
    },
    2013: {
        "ventas": 265
    },
    2014: {
        "ventas": 284
    }
}
precio_inicial = []
descuento = []
for i in b: 
    precio_inicial.append(fechas[i]["ventas"])
descuento.append(np.multiply(precio_inicial,0.10))
precio_final = np.subtract(precio_inicial, descuento)


print("Precio inicial: {} \nPrecio con 10% de descuento: {}".format(precio_inicial, precio_final))

Precio inicial: [220, 231, 184, 265, 284] 
Precio con 10% de descuento: [[198.  207.9 165.6 238.5 255.6]]


In [17]:
a = 1
descuento = 0
print(f"Precio inicial: {a} \nPrecio con descuento: {descuento}")


Precio inicial: 1 
Precio con descuento: 0


#### 8. Escribir una función que reciba un diccionario con las notas de los alumno de un curso y devuelva una serie con la nota mínima, la máxima, media y la desviación típica

In [18]:
notas = {'Jaime':2,
         'Adrián': 10,
         'Pablo': 4,
         'Jorge': 3,
         'David': 7,
         'Manuel': 9,
         'Sara': 6,
         'Lucía': 3}

def calcular_notas(notas):
    nota_max = 0
    nota_min = 10
    for i in notas :
        a = notas.get(i)
        if nota_max < a: nota_max = a
        if nota_min > a: nota_min = a
    
    return "Nota máxima:", nota_max, "Nota mínima:", nota_min,"Nota media:", "Desviación típica:"
calcular_notas(notas)

('Nota máxima:', 10, 'Nota mínima:', 2, 'Nota media:', 'Desviación típica:')

#### 9. Escribir una función que reciba un diccionario con las notas de los alumnos de un curso y devuelva una serie con las notas de los alumnos aprobados ordenadas de mayor a menor.

In [46]:
notas = {'Jaime':2,
         'Adrián': 10,
         'Pablo': 4,
         'Jorge': 3,
         'David': 7,
         'Manuel': 9,
         'Sara': 6,
         'Lucía': 3}

def calcular_notas(notas):
    a = []
    for i in notas :
        a.append(notas.get(i))
    a.sort(reverse = True)
    return a
calcular_notas(notas)

[10, 9, 7, 6, 4, 3, 3, 2]